version: '3.8'

services:
  python:
    build:
      context: .
      dockerfile: python.Dockerfile
    container_name: python_container
    volumes:
      - ./code:/usr/src/app
    command: python /usr/src/app/script.py

  node:
    build:
      context: .
      dockerfile: node.Dockerfile
    container_name: node_container
    volumes:
      - ./code:/usr/src/app
    command: node /usr/src/app/script.js

  java:
    build:
      context: .
      dockerfile: java.Dockerfile
    container_name: java_container
    volumes:
      - ./code:/usr/src/app
    command: java /usr/src/app/HelloWorld

  c:
    build:
      context: .
      dockerfile: c.Dockerfile
    container_name: c_container
    volumes:
      - ./code:/usr/src/app
    command: /usr/src/app/a.out
